ERROR  策略文件vnpy.app.cta_strategy_pro.strategies.strategy_renko_reverse加载失败，触发异常：
Traceback (most recent call last):
  File "D:\lee_vnpy\vnpy\app\cta_strategy_pro\portfolio_testing.py", line 773, in load_strategy_class_from_module
    module = importlib.import_module(module_name)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\lee_vnpy\vnpy\app\cta_strategy_pro\strategies\strategy_renko_reverse.py", line 11, in <module>
    from vnpy.app.cta_strategy_pro import (
ImportError: cannot import name 'CtaPosition' from 'vnpy.app.cta_strategy_pro' (D:\lee_vnpy\vnpy\app\cta_strategy_pro\__init__.py)

ERROR  策略文件vnpy.app.cta_strategy_pro.strategies.strategy_triple_ma_v1加载失败，触发异常：
Traceback (most recent call last):
  File "D:\lee_vnpy\vnpy\app\cta_strategy_pro\portfolio_testing.py", line 773, in load_strategy_class_from_module
    module = importlib.import_module(module_name)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\lee_vnpy\vnpy\app\cta_strategy_pro\strategies\strategy_triple_ma_v1.py", line 13, in <module>
    from vnpy.app.cta_strategy_pro import (
ImportError: cannot import name 'CtaPosition' from 'vnpy.app.cta_strategy_pro' (D:\lee_vnpy\vnpy\app\cta_strategy_pro\__init__.py)

