INFO  [2020-03-26 16:11:11,752][engine.py:1701] 加载策略类vnpy.app.cta_strategy_pro.strategies.turtle_signal_strategy.TurtleSignalStrategy
INFO  [2020-03-26 16:11:11,757][engine.py:1701] 加载策略类vnpy.app.cta_strategy_pro.strategies.turtle_signal_strategy_v2.TurtleSignalStrategy_v2
INFO  [2020-03-26 16:11:11,759][engine.py:1701] CTA策略引擎初始化成功
INFO  [2020-03-26 16:11:28,209][engine.py:1701] 开始添加策略类TurtleSignalStrategy，实例名:test_i2005
INFO  [2020-03-26 16:11:28,213][engine.py:1701] test_i2005开始执行初始化
INFO  [2020-03-26 16:11:28,231][engine.py:1701] test_i2005初始化完成
ERROR  [2020-03-26 17:08:28,007][engine.py:1701] test_i2005已经完成初始化，禁止重复操作
ERROR  [2020-03-26 17:08:31,233][engine.py:1701] test_i2005已经启动，请勿重复操作
INFO  [2020-03-26 17:22:28,729][engine.py:1701] 调用test_i2005的on_stop,停止交易
INFO  [2020-03-26 17:22:28,732][engine.py:1701] 撤销test_i2005所有委托
INFO  [2020-03-26 17:22:45,933][engine.py:1701] test_i2005策略实例已处于停止交易状态
CRITICAL  [2020-03-26 17:24:45,756][engine.py:1701] 策略文件vnpy.app.cta_strategy_pro.strategies.strategy_triple_ma_v1加载失败，触发异常：
Traceback (most recent call last):
  File "C:\vnpy\vnpy\app\cta_strategy_pro\engine.py", line 1228, in load_strategy_class_from_module
    module = importlib.import_module(module_name)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\vnpy\vnpy\app\cta_strategy_pro\strategies\strategy_triple_ma_v1.py", line 13, in <module>
    from vnpy.app.cta_strategy_pro import (
ImportError: cannot import name 'CtaPosition' from 'vnpy.app.cta_strategy_pro' (C:\vnpy\vnpy\app\cta_strategy_pro\__init__.py)

CRITICAL  [2020-03-26 17:24:45,770][engine.py:1701] 策略文件vnpy.app.cta_strategy_pro.strategies.strategy_triple_ma_v2加载失败，触发异常：
Traceback (most recent call last):
  File "C:\vnpy\vnpy\app\cta_strategy_pro\engine.py", line 1228, in load_strategy_class_from_module
    module = importlib.import_module(module_name)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\vnpy\vnpy\app\cta_strategy_pro\strategies\strategy_triple_ma_v2.py", line 11, in <module>
    from vnpy.app.cta_strategy_pro import (
ImportError: cannot import name 'CtaPolicy' from 'vnpy.app.cta_strategy_pro' (C:\vnpy\vnpy\app\cta_strategy_pro\__init__.py)

INFO  [2020-03-26 17:24:45,773][engine.py:1701] 加载策略类vnpy.app.cta_strategy_pro.strategies.turtle_signal_strategy.TurtleSignalStrategy
INFO  [2020-03-26 17:24:45,776][engine.py:1701] 加载策略类vnpy.app.cta_strategy_pro.strategies.turtle_signal_strategy_v2.TurtleSignalStrategy_v2
INFO  [2020-03-26 17:24:45,778][engine.py:1701] 开始添加策略类TurtleSignalStrategy，实例名:test_i2005
INFO  [2020-03-26 17:24:45,781][engine.py:1701] test_i2005开始执行初始化
INFO  [2020-03-26 17:24:45,781][engine.py:1701] CTA策略引擎初始化成功
INFO  [2020-03-26 17:24:45,799][engine.py:1701] test_i2005初始化完成
ERROR  [2020-03-26 17:25:31,297][engine.py:1701] 策略test_i2005移除失败，请先停止
ERROR  [2020-03-26 17:25:36,980][engine.py:1701] test_i2005已经完成初始化，禁止重复操作
ERROR  [2020-03-26 17:25:37,478][engine.py:1701] test_i2005已经完成初始化，禁止重复操作
ERROR  [2020-03-26 17:25:38,036][engine.py:1701] test_i2005已经完成初始化，禁止重复操作
INFO  [2020-03-26 17:25:38,895][engine.py:1701] 调用test_i2005的on_stop,停止交易
INFO  [2020-03-26 17:25:38,897][engine.py:1701] 撤销test_i2005所有委托
INFO  [2020-03-26 17:26:19,123][engine.py:1701] test_i2005策略实例已处于停止交易状态
CRITICAL  [2020-03-26 17:29:03,456][engine.py:1701] 策略文件vnpy.app.cta_strategy_pro.strategies.strategy_triple_ma_v1加载失败，触发异常：
Traceback (most recent call last):
  File "C:\vnpy\vnpy\app\cta_strategy_pro\engine.py", line 1228, in load_strategy_class_from_module
    module = importlib.import_module(module_name)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\vnpy\vnpy\app\cta_strategy_pro\strategies\strategy_triple_ma_v1.py", line 13, in <module>
    from vnpy.app.cta_strategy_pro import (
ImportError: cannot import name 'CtaPosition' from 'vnpy.app.cta_strategy_pro' (C:\vnpy\vnpy\app\cta_strategy_pro\__init__.py)

CRITICAL  [2020-03-26 17:29:03,465][engine.py:1701] 策略文件vnpy.app.cta_strategy_pro.strategies.strategy_triple_ma_v2加载失败，触发异常：
Traceback (most recent call last):
  File "C:\vnpy\vnpy\app\cta_strategy_pro\engine.py", line 1228, in load_strategy_class_from_module
    module = importlib.import_module(module_name)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\vnpy\vnpy\app\cta_strategy_pro\strategies\strategy_triple_ma_v2.py", line 11, in <module>
    from vnpy.app.cta_strategy_pro import (
ImportError: cannot import name 'CtaPolicy' from 'vnpy.app.cta_strategy_pro' (C:\vnpy\vnpy\app\cta_strategy_pro\__init__.py)

INFO  [2020-03-26 17:29:03,467][engine.py:1701] 加载策略类vnpy.app.cta_strategy_pro.strategies.turtle_signal_strategy.TurtleSignalStrategy
INFO  [2020-03-26 17:29:03,470][engine.py:1701] 加载策略类vnpy.app.cta_strategy_pro.strategies.turtle_signal_strategy_v2.TurtleSignalStrategy_v2
INFO  [2020-03-26 17:29:03,471][engine.py:1701] 开始添加策略类TurtleSignalStrategy，实例名:test_i2005
INFO  [2020-03-26 17:29:03,474][engine.py:1701] test_i2005开始执行初始化
INFO  [2020-03-26 17:29:03,474][engine.py:1701] CTA策略引擎初始化成功
INFO  [2020-03-26 17:29:03,489][engine.py:1701] 找不到合约i2005.DCE信息，尝试请求所有接口
INFO  [2020-03-26 17:29:03,489][engine.py:1701] test_i2005初始化完成
INFO  [2020-03-26 17:29:14,279][engine.py:1701] 调用test_i2005的on_stop,停止交易
INFO  [2020-03-26 17:29:14,281][engine.py:1701] 撤销test_i2005所有委托
CRITICAL  [2020-03-26 17:29:57,867][engine.py:1701] 策略文件vnpy.app.cta_strategy_pro.strategies.strategy_triple_ma_v1加载失败，触发异常：
Traceback (most recent call last):
  File "C:\vnpy\vnpy\app\cta_strategy_pro\engine.py", line 1228, in load_strategy_class_from_module
    module = importlib.import_module(module_name)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\vnpy\vnpy\app\cta_strategy_pro\strategies\strategy_triple_ma_v1.py", line 13, in <module>
    from vnpy.app.cta_strategy_pro import (
ImportError: cannot import name 'CtaPosition' from 'vnpy.app.cta_strategy_pro' (C:\vnpy\vnpy\app\cta_strategy_pro\__init__.py)

CRITICAL  [2020-03-26 17:29:57,878][engine.py:1701] 策略文件vnpy.app.cta_strategy_pro.strategies.strategy_triple_ma_v2加载失败，触发异常：
Traceback (most recent call last):
  File "C:\vnpy\vnpy\app\cta_strategy_pro\engine.py", line 1228, in load_strategy_class_from_module
    module = importlib.import_module(module_name)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\vnpy\vnpy\app\cta_strategy_pro\strategies\strategy_triple_ma_v2.py", line 11, in <module>
    from vnpy.app.cta_strategy_pro import (
ImportError: cannot import name 'CtaPolicy' from 'vnpy.app.cta_strategy_pro' (C:\vnpy\vnpy\app\cta_strategy_pro\__init__.py)

INFO  [2020-03-26 17:29:57,880][engine.py:1701] 加载策略类vnpy.app.cta_strategy_pro.strategies.turtle_signal_strategy.TurtleSignalStrategy
INFO  [2020-03-26 17:29:57,883][engine.py:1701] 加载策略类vnpy.app.cta_strategy_pro.strategies.turtle_signal_strategy_v2.TurtleSignalStrategy_v2
INFO  [2020-03-26 17:29:57,885][engine.py:1701] 开始添加策略类TurtleSignalStrategy，实例名:test_i2005
INFO  [2020-03-26 17:29:57,888][engine.py:1701] test_i2005开始执行初始化
INFO  [2020-03-26 17:29:57,890][engine.py:1701] CTA策略引擎初始化成功
INFO  [2020-03-26 17:29:57,890][engine.py:1701] 找不到合约i2005.DCE信息，尝试请求所有接口
INFO  [2020-03-26 17:29:57,905][engine.py:1701] test_i2005初始化完成
INFO  [2020-03-26 17:30:54,082][engine.py:1701] 调用test_i2005的on_stop,停止交易
INFO  [2020-03-26 17:30:54,083][engine.py:1701] 撤销test_i2005所有委托
